version: '3.8'

services:
  backend:
    image: shafeekuralabs/ecommerce-backend:latest
    environment:
      - DEBUG=0
      - DB_NAME=ecommerce
      - DB_HOST=${rds_address}
      - DB_USER=${db_username}
      - DB_PASSWORD=${db_password}
      - DB_PORT=5432
      - DJANGO_SETTINGS_MODULE=my_project.settings
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: shafeekuralabs/ecommerce-frontend:latest
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s